[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "argus-dns"
version = "0.1.0"
description = "A National DNS Caching-Server Health and Cache-Poisoning Monitoring System."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dnspython>=2.6.1",
    "PyYAML>=6.0.1",
]

[project.scripts]
argus = "argus.__main__:main"

[tool.setuptools]
packages = ["argus"]
